# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches: 
    include:
    - master
  paths:
    exclude:
    - README.md
    - .gitignore

pr:
- master

jobs:
- job: build_linux
  pool:
    vmImage: 'ubuntu-latest'

steps:
- task: SonarCloudPrepare@1
  displayName: sonarcloud prepare analysis
  inputs:
    SonarCloud: 'sonarcloud-pamelasoulis'
    organization: '2006-jun15-net'
    scannerMode: 'MSBuild'
    projectKey: '2006-jun15-net_pamela-soulis-project1'
    projectName: 'Pamela Soulis project 1'

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: node install


- script: npm install
  displayName: npm install

- script: npx ng build --prod
  displayName: ng build
  
- task: SonarCloudAnalyze@1
  displayName: sonarcloud run analysis

- task: SonarCloudPublish@1
  displayName: publish sonarcloud result
  inputs:
    pollingTimeoutSec: '300'






