# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches: 
    include:
    - master
  paths:
    exclude:
    - README.md
    - .gitignore

pr:
- master

jobs:
- job: build_linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'ar-dk-ps-sonarcloud'
      organization: '2006-jun15-net'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: '2006-jun15-net_ar-dk-ps-project2-site'
      projectName: 'ar-dk-ps-project2-site'
      

  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: node install


  - script: npm install
    displayName: npm install

  - script: npm build --prod --build-optimizer
    displayName: npm build
  

  - task: SonarCloudAnalyze@1
    displayName: sonarcloud run analysis

  - task: SonarCloudPublish@1
    displayName: publish sonarcloud result
    inputs:
      pollingTimeoutSec: '300'

  - task: AzureRmWebAppDeployment@4
    displayName: azure app service deploy
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1(3edca897-65af-4673-84e4-b3d1c79e363a)'
      appType: 'webApp'
      WebAppName: 'pamela-soulis-project2'
      packageForLinux: '$(System.DefaultWorkingDirectory)/publish'




